name: Run Unit tests
# Run this workflow when we dev or main changes
# because of a push or is about the be changed
# by a pull request

on:
  push:
    branches: [test]
  pull_request: 
    branches: [test]

jobs:
### Run Unit  tests
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      # run the npm build command (not used in our project)
    - run: npm run build --if-present
      # install pm2 so we can run our node.js
      # based backend without blocking the terminal
      # run our Node.js based server/backend/REST-api using pm2
    - run: npm start backend/index.js
      # Install Chrome
    - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - run: sudo apt install ./google-chrome-stable_current_amd64.deb
    - run: npm install jest 
      # run the unit tests
    - run: npm test         